### ISSUE TITLE
future improvements required

### ISSUE THREAD

**Issue by struan** [mysociety/ceuk-marking#124]
This is a catchall ticket for future improvements based on the 2023 process.

- [Handle multiple versions/years of questions/sections/assignments](https://github.com/mysociety/ceuk-marking/issues/132)
- ~default questions to last years answers to minimise volunteer work? (this might not be all questions)~ – we’ve agreed with CEUK that they don’t want to "default" to last year’s answers, so we’ll allow them to view and copy instead, see below
- [council right of reply export option](https://github.com/mysociety/ceuk-marking/issues/77)

### UI changes

- [enable viewing/copying over previous answers to question](https://github.com/mysociety/ceuk-marking/issues/133)
- [make saving process clearer](https://github.com/mysociety/ceuk-marking/issues/135)

### Improve volunteer management

- [Write interface to enable management of volunteer assignments.](https://github.com/mysociety/ceuk-marking/issues/134)
 Currently this is done in the django admin or through importing spreadsheets. Either way it's not well documented and it's not very obvious how to do it, or how to update assignments. Equally, assigning a volunteer to a particular stage is also not easy.
- [Allow easy mass removal/deactivation of volunteers based on stage](https://github.com/mysociety/ceuk-marking/issues/136).

**Comment by zarino** [comment]
Closing this ticket, as we’ve broken out all the points into their own tickets (see above).
