### ISSUE TITLE
Display answers to previous years question next to this years question in First Mark interface

### ISSUE THREAD

**Issue by struan** [mysociety/ceuk-marking#133]
Have a button to copy previous year's answer to this year.

Need to make sure that it's for the correct question – so depends upon #142 

Also need to highlight if anything about the question has changed.

~May also need an option to display notes about the previous years answer.~

**Comment by struan** [comment]
CEUK are going to answer the few questions that have specific changes needed before they are available to the markers rather than having any notes on previous year's questions

**Comment by zarino** [comment]
Related – #146 (mark broken plan/evidence links)
