### ISSUE TITLE
Ticket up second marking, right to reply process.

### ISSUE THREAD

**Issue by struan** [mysociety/ceuk-marking#18]

**Comment by JenMysoc** [comment]
What info do we need? We can ask today at our weekly catchup

**Comment by struan** [comment]
I believe we asked for a spec from them for this week.

**Comment by JenMysoc** [comment]
At the bottom of: https://docs.google.com/document/d/1lX66hNRH4hZxh6otbDEofTRfI-jERRK4kL_nTOKHv9g/edit

**Comment by struan** [comment]
See https://github.com/mysociety/ceuk-marking/milestone/2 for tickets
