### ISSUE TITLE
Decide format for council marking

### ISSUE THREAD

**Issue by struan** [mysociety/ceuk-marking#21]
Choice are:
* Excel spreadsheet per council
* use web tool.

### Excel

Excel has the advantage that councils largely are familiar with it, there's no setting up accounts etc and no firewall issues which are likely to be a problem.

Disadvantages are we need to write something to export and import excel. Potential for weird/bad data increases as councils can do what they want to excel. Have to email out excel spread sheets which again is a potential issue.

### Web form

Advantages are we have a lot of the code, we control the inputs, no export/import required.

Disadvantages: council staff need to create an account and log on and get to grips with the interface. We need to write the code to enable them to add corrections etc. Council firewalls are often pretty strict so council staff may not be able to access it.

### Other points

Regardless we'll need to send out an email inviting them to mark.

**Comment by ajparsons** [comment]
My gut says spreadsheets. 

Part of the reason we've gone for Excel previously is this knowing that if even 1 or 2 can't access it, we'll need to provide it in a different format. 

If it *is* only 1 or 2 though, we would only need an export process - as someone could enter a few of them manually. But this feels like a gamble assuming it is only one or two.

Previously we used automation to lock down the spreadsheets as much as possible. Most of this can be done in linux, but adding a front page sheet with an image could only be done in Windows for some reason (without the image it's fine). Cover sheets are created automatically as part of the dataset creation process, so some working code around on that.

If we were sending credentials, we'd need to personalise all emails anyway.

**Comment by struan** [comment]
We have decided on a web page. CEUK did some checking with councils and those contacted didn't forsee any issues with this. This is partly because it removes the potential for error/issues with the export/import step of spreadsheets and also because, as with initial marking, we'll have more control of what's happening so should be able to prevent errors.
