### ISSUE TITLE
Import national transport data

### ISSUE THREAD

**Issue by struan** [mysociety/ceuk-marking#51]
> Active Travel England - https://www.gov.uk/government/publications/local-authority-active-travel-capability-ratings
> 
> This is slightly awkward as the names are different and in a table which we can copy and paste into a spreadsheet.
> 
> Bus ridership data - attached as a CSV and found on Tab Bus01f. (see original email for data)
> It can also be found here to download yourself: https://www.gov.uk/government/statistical-data-sets/bus-statistics-data-tables#local-bus-passenger-journeys-bus01

**Comment by struan** [comment]
[bus01 (1).ods](https://github.com/mysociety/ceuk-marking/files/10970066/bus01.1.ods)

**Comment by zarino** [comment]
Closing in favour of #102
