### ISSUE TITLE
GRACE support ticket: Incorrect numbers in audit progress bars

### ISSUE THREAD

**Issue by zarino** [mysociety/ceuk-marking#86]
(Copied from the GRACE support tracker spreadsheet)

On [Buildings & Heating & Green Skills (CA) authority audit progress screen](https://marking.councilclimatescorecards.uk/section/audit/Buildings%20&%20Heating%20&%20Green%20Skills%20(CA)/authorities/), for some of the authorities it says 8 out 7 Qs have been answered, but there are 10 questions in this section (1–8, 9a, 9b).

<img width="1503" alt="Screenshot 2023-06-07 at 17 09 13" src="https://github.com/mysociety/ceuk-marking/assets/739624/a9eafac9-fc0e-44c6-b8d9-5599ad8c0674">

Meanwhile, for the Greater London Authority, it says all questions are answered, but that’s not true, only 6 questions have been answered, questions 2, 9a, and 9b have been left blank.

**Comment by zarino** [comment]
@alexander-griffen is this related to #81 / #83 ?

**Comment by struan** [comment]
From sheet:

> Sections in the Audit are still showing "3 out of 2" or "9 out of 8" when auditors are completing their section.
> 
> See above numbers problem - which was fixed for Buildings & Heating but effects every section bar Waste & Food
